import React, { useState } from 'react';
import { motion } from 'motion/react';
import { Database, X, Check, Copy, Sparkles, Code2, ShieldCheck } from 'lucide-react';
import { TRANSLATIONS, Language } from '../translations';

interface DatabaseWizardModalProps {
  isOpen: boolean;
  onClose: () => void;
  language: Language;
}

export default function DatabaseWizardModal({
  isOpen,
  onClose,
  language
}: DatabaseWizardModalProps) {
  const t = TRANSLATIONS[language];
  const [dbType, setDbType] = useState<'Firebase' | 'Supabase'>('Firebase');
  const [projectName, setProjectName] = useState("Tetikasa 1");
  
  // Firebase Inputs
  const [fbApiKey, setFbApiKey] = useState("");
  const [fbProjectId, setFbProjectId] = useState("");
  
  // Supabase Inputs
  const [sbUrl, setSbUrl] = useState("");
  const [sbAnonKey, setSbAnonKey] = useState("");

  const [generatedSnippet, setGeneratedSnippet] = useState("");
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleGenerate = () => {
    let snippet = "";
    if (dbType === 'Firebase') {
      snippet = `<!-- Firebase Configuration Auto-Generated by DEVWEB IA -->
<script type="module">
  import { initializeApp } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
  import { getFirestore, collection, addDoc, getDocs } from "https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";

  const firebaseConfig = {
    apiKey: "${fbApiKey || 'YOUR_API_KEY_HERE'}",
    projectId: "${fbProjectId || 'YOUR_PROJECT_ID_HERE'}",
    authDomain: "${fbProjectId ? fbProjectId + '.firebaseapp.com' : 'YOUR_PROJECT_ID.firebaseapp.com'}"
  };

  const app = initializeApp(firebaseConfig);
  const db = getFirestore(app);

  // Maimaim-poana ny hitahiry sy haka data:
  window.saveToCloud = async (collectionName, data) => {
    try {
      const docRef = await addDoc(collection(db, collectionName), {
        ...data,
        createdAt: new Date().toISOString()
      });
      console.log("Document successfully written with ID: ", docRef.id);
      return docRef.id;
    } catch (e) {
      console.error("Error adding document: ", e);
    }
  };
</script>`;
    } else {
      snippet = `<!-- Supabase Configuration Auto-Generated by DEVWEB IA -->
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>
<script>
  const supabaseUrl = "${sbUrl || 'https://your-supabase-url.supabase.co'}";
  const supabaseKey = "${sbAnonKey || 'your-supabase-anon-key'}";
  const supabase = supabase.createClient(supabaseUrl, supabaseKey);

  // Maimaim-poana ny hitahiry sy haka data:
  window.saveToSupabase = async (tableName, data) => {
    try {
      const { data: res, error } = await supabase
        .from(tableName)
        .insert([data]);
      if (error) throw error;
      console.log("Inserted row successfully:", res);
      return res;
    } catch (e) {
      console.error("Error inserting data into Supabase:", e.message);
    }
  };
</script>`;
    }
    setGeneratedSnippet(snippet);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedSnippet);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 bg-slate-950/80 flex items-center justify-center z-50 p-4 backdrop-blur-sm">
      <motion.div
        initial={{ scale: 0.95, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        exit={{ scale: 0.95, opacity: 0 }}
        className="max-w-xl w-full bg-slate-900 border border-slate-800 rounded-3xl p-6 text-slate-100 shadow-2xl relative"
      >
        <button
          id="wizard-close-btn"
          onClick={onClose}
          className="absolute right-4 top-4 p-2 bg-slate-850 hover:bg-slate-800 rounded-full text-slate-400 hover:text-white cursor-pointer"
        >
          <X className="w-4 h-4" />
        </button>

        {/* Header */}
        <div className="flex items-center gap-3 mb-6">
          <div className="p-2 bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 rounded-xl">
            <Database className="w-5 h-5 animate-pulse" />
          </div>
          <div>
            <h3 className="text-lg font-bold font-display tracking-tight text-white">
              {t.databaseWizard}
            </h3>
            <p className="text-xs text-slate-400">
              {t.wizardInstructions}
            </p>
          </div>
        </div>

        {/* Database type selection */}
        <div className="grid grid-cols-2 gap-3 mb-5 p-1 bg-slate-950 rounded-2xl border border-slate-800">
          <button
            id="wizard-select-firebase"
            onClick={() => {
              setDbType('Firebase');
              setGeneratedSnippet("");
            }}
            className={`py-2.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
              dbType === 'Firebase' 
                ? 'bg-amber-500 text-slate-950 font-black' 
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Google Firebase
          </button>
          
          <button
            id="wizard-select-supabase"
            onClick={() => {
              setDbType('Supabase');
              setGeneratedSnippet("");
            }}
            className={`py-2.5 rounded-xl text-xs font-bold transition-all cursor-pointer ${
              dbType === 'Supabase' 
                ? 'bg-indigo-500 text-white font-black' 
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Supabase Postgres
          </button>
        </div>

        {/* Configuration inputs */}
        <div className="space-y-4 mb-6">
          {dbType === 'Firebase' ? (
            <div className="space-y-3">
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Firebase API Key</label>
                <input
                  id="wizard-fb-apikey"
                  type="text"
                  placeholder="AIzaSy..."
                  value={fbApiKey}
                  onChange={(e) => setFbApiKey(e.target.value)}
                  className="w-full p-2.5 text-xs bg-slate-950 border border-slate-800 rounded-xl focus:outline-none focus:ring-1 focus:ring-amber-500 text-white placeholder:text-slate-700"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Project ID</label>
                <input
                  id="wizard-fb-projectid"
                  type="text"
                  placeholder="my-cool-app-123"
                  value={fbProjectId}
                  onChange={(e) => setFbProjectId(e.target.value)}
                  className="w-full p-2.5 text-xs bg-slate-950 border border-slate-800 rounded-xl focus:outline-none focus:ring-1 focus:ring-amber-500 text-white placeholder:text-slate-700"
                />
              </div>
            </div>
          ) : (
            <div className="space-y-3">
              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Supabase URL</label>
                <input
                  id="wizard-sb-url"
                  type="text"
                  placeholder="https://xxxx.supabase.co"
                  value={sbUrl}
                  onChange={(e) => setSbUrl(e.target.value)}
                  className="w-full p-2.5 text-xs bg-slate-950 border border-slate-800 rounded-xl focus:outline-none focus:ring-1 focus:ring-indigo-500 text-white placeholder:text-slate-700"
                />
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-bold text-slate-400 uppercase tracking-widest block">Anon Key</label>
                <input
                  id="wizard-sb-key"
                  type="text"
                  placeholder="eyJhbGciOi..."
                  value={sbAnonKey}
                  onChange={(e) => setSbAnonKey(e.target.value)}
                  className="w-full p-2.5 text-xs bg-slate-950 border border-slate-800 rounded-xl focus:outline-none focus:ring-1 focus:ring-indigo-500 text-white placeholder:text-slate-700"
                />
              </div>
            </div>
          )}

          <button
            id="wizard-generate-btn"
            onClick={handleGenerate}
            className="w-full py-2.5 bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white font-bold rounded-xl text-xs transition-colors cursor-pointer flex items-center justify-center gap-1.5"
          >
            <Code2 className="w-4 h-4" />
            <span>{t.generateSnippets}</span>
          </button>
        </div>

        {/* Output snippet box */}
        {generatedSnippet && (
          <div className="space-y-2.5">
            <div className="flex justify-between items-center bg-slate-950 px-3 py-1.5 rounded-t-xl border-t border-x border-slate-800 text-[10px] font-bold text-slate-400">
              <span>AMPIDIRO ANATY PROMPT-NAO</span>
              <button
                id="wizard-copy-btn"
                onClick={handleCopy}
                className="flex items-center gap-1 hover:text-white transition-colors"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>
            </div>
            <textarea
              readOnly
              value={generatedSnippet}
              className="w-full h-32 p-3 bg-slate-950 border border-slate-800 rounded-b-xl font-mono text-[10px] text-emerald-400 focus:outline-none"
            />
            <p className="text-[10px] text-slate-500 italic flex items-center gap-1">
              <ShieldCheck className="w-3.5 h-3.5 text-slate-500" /> Handefesina any amin'ny Gemini AI ity kaody ity mba hampifandray ny database-nao mivantana.
            </p>
          </div>
        )}

      </motion.div>
    </div>
  );
}
